src/js/Form.js

renamed $dataNodes to expected dataNodes

---

app.js
src/js/Form-model.js
src/js/Form.js
test/spec/formmodel.spec.js

Convert form validation to use Promises.

---

package.json
src/js/Form-model.js
src/js/Form.js
src/js/file-manager.js
src/widget/geo/geopicker.js

This should resolve issue #327

ES6 Promise/A+; replace `Q` with `lie`

---

src/js/Form.js

Add JSDoc for `FormView.prototype.pages.next()`

---

src/js/Form.js

On form init, re-run field calculations after event handlers are set

---

src/js/Form-model.js
src/js/input.js
src/js/types.js
src/widget/file/filepicker.js

Not sure if this is a style thing 🙂

Simplify ternary expressions

---

src/js/file-manager.js

Expose fileManager.isTooLarge()

---

src/js/fake-translator.js
src/js/file-manager.js
src/js/translated-error.js
src/widget/file/filepicker.js

Translate user-facing messages in filepicker

---

build/index.html

Clean up inconsistencies in spacing and tabs vs spaces in build/index.html

Whitespace cleanup

---

src/js/fake-translator.js
src/js/file-manager.js
src/widget/file/filepicker.js

Remove filemanager.isSupported() check

---

src/js/file-manager.js

Add documentation for getFileUrl() args

---

src/js/xpath-evaluator-binding.js

...or maybe the other quote mark should be removed? 🙂

Add missing quote mark in example code in comment

---

src/widget/url/url-widget.js

added: rel="noopener" to URL widget links

---

src/sass/core/_main.scss

fixed: Grid theme options with appearance horizontal break out of cell

---

src/js/fake-translator.js
src/js/itemset.js
test/forms/external-data-v2.xml
test/helpers/load-form.js
test/spec/itemset.spec.js

[510](https://github.com/enketo/enketo-core/issues/510) 
Preview 
I change the color to highlight the warning.

added: Show warning if select_multiple value has spaces

---

src/js/file-manager.js
src/widget/file/filepicker.js

[#578](https://github.com/enketo/enketo-core/issues/578)

Update support for max-pixels attribute

---

src/widget/file/filepicker.js

[#578](https://github.com/enketo/enketo-core/issues/578)

fixed: fileManager.getCurrentFiles using asynchronous code for synchronous result( offline mode )

---

src/widget/datetime/datetimepicker-extended.js
src/widget/time/timepicker.js

Fix three bugs on time picker and datetime widget

---

src/js/widgets.js
src/sass/core/_widgets.scss
src/widget/range/range-widget.js
src/widget/rating/rating.js
src/widget/rating/rating.scss
test/forms/range.xml
test/spec/widget.rating.spec.js

add: range widget(rating appearance)

---

package-lock.json
package.json
src/js/extend.js
src/js/xpath-evaluator-binding.js

Replaces enketo-xpathjs with openrosa-xpath-evaluator (beta version).

Replaces enketo-xpathjs

---

src/widget/text-print/text-print.js

[#303](https://github.com/OpenClinica/enketo-express-oc/issues/303)
[OC-12208](https://jira.openclinica.com/browse/OC-12208)

fixed: OC: Hide URL input from print view

---

src/widget/textarea/textarea.js

[312](https://github.com/OpenClinica/enketo-express-oc/issues/312) [OC-12474](https://jira.openclinica.com/browse/OC-12474)

fixed: OC: include textarea on text-print widget selector(#312)

---

src/js/event.js
src/sass/core/_print.scss
src/widget/text-print/text-print.js
src/widget/text-print/text-print.scss

[#312](https://github.com/OpenClinica/enketo-express-oc/issues/312) 
form-model.js and input.js updated when I run `grunt jsbeautifier:fix` should I exclude those files?

fiixed: OC: Issue text area not resize correctly when printing

---

src/widget/date/datepicker-extended.js

fix FF datepicker label 

---

src/widget/image-map/image-map.js

[#378](https://github.com/OpenClinica/enketo-express-oc/issues/378)

update: query selector to target element with '.option-wrapper' only

---

README.md
package-lock.json
package.json
src/widget/range/range-widget.js
test/forms/range.xml
test/spec/widget.range.spec.js
tutorials/20-development.md

Addresses #771.
I also updated the Node version in the development docs, if this is incorrect/unwanted I can revert. And I pinned the version for [Volta](https://volta.sh/) users in package.json, which again I can revert if unwanted.

fixed: Range value doesn't display when draft (offline) survey is loaded

---

tutorials/20-development.md

Mainly a small note about npm 7.

Improve development guide prerequisites info

---

src/sass/grid/_variables.scss

Increase grid theme max width to 13

---

.github/workflows/npmjs.yml
test/spec/form.spec.js

Same as https://github.com/enketo/enketo-transformer/pull/136

Improve build speed

---

src/js/itemset.js
test/forms/select-dynamic-readonly.xml
test/spec/itemset.spec.js

Disable <option>s for readonly <select>s with itemsets

---

src/js/form-model.js
src/js/type-def.js
test/forms/missing-external-instance.xml
test/spec/form.spec.js
test/spec/formmodel.spec.js

Part of enketo/enketo-express#363

Fix: improve error messages for missing external instances

---

src/js/form.js
test/forms/SOAR_facilitysurvey_full_2017May11_Kenya.xml

Broken out from #881 as requested by @MartijnR. Branched from #886 as that makes it easier to evaluate the performance difference.

Form init performance: recalculate repeats once

---

CHANGELOG.md
package-lock.json
package.json
src/js/form.js

Opening as draft and also holding off on updating docs, pending #870.

Prepare to release 6.1.0

---

src/widget/geo/geopicker.js
test/forms/setvalue-setgeopoint-geopoint.xml
test/spec/widget.geo.spec.js

Fixes enketo/enketo-express#431

Fix: rendering unexpected geopoint widget for setvalue actions within an input

---

src/widget/number-input/decimal-input.js
src/widget/number-input/integer-input.js
src/widget/number-input/number-input.js
test/spec/widget.number-input.spec.js

Fix: localized numeral entry by keyboard in number input widgets

---

src/widget/number-input/number-input.js

gracefully handle undefined key (#977)
