enketo/enketo-core

.travis.yml
I don't think this is necessary any more, as all the submodules seem to be gone.
=> Remove `git submodule update` call from Travis build

Gruntfile.js
Pretty sure it's no longer necessary to recompile SASS if `config.json` changes.
=> Don't include `config.json` in the SASS watch-list

src/js/FormModel.js
Just a suggestion - these messages come up in scary red writing in my console, even though the message is to be ignored.  Seems more appropriate to me to make these plain `console.log` messages.
=> Change logging level to `log` if errors are deliberately ignored

src/js/Form.js
Just a minor change that I noticed when rebasing the `medic-mobile` fork - seems more logical to move event propagation to the event handler, as described below.
-----
Move the triggering of `'valuechange.enketo'` out of `FormView.validateInput()`, and into the event handler for `'change.file validate'`.
* this is the only place `eventType` can have a value of `'change'`
* this makes the behaviour of `validateInput()` more discrete
=> Move event handling/retrigger out of `FormView.validateInput()`

src/js/Form.js
This changes the `pages.next()` function to return a `Promise`, wrapping one of the following values:
value | meaning
-----|-----
`false` | validation failed
`true` | validation passed, but the page did not change
`number` | the index into `$activePages` of the new page
In our app, we want to add an item to the browser history representing each page of the form.  With this change, code such as this can be written:
```javascript
form.getView().pages.next()
.then( function( newPageIndex ) {
window.history.pushState( { enketo_page_number: newPageIndex - 1 }, '' );
} );
...
$( window ).on( 'popstate', function( event ) {
var pages, targetPage;
if ( event.originalEvent.state && event.originalEvent.state.enketo_page_number ) {
targetPage = event.originalEvent.state.enketo_page;
pages = …
```
=> Return a promise wrapping new page index when turning to next page

src/widget/analog-scale/analog-scalepicker.js, src/widget/date/datepicker-extended.js, src/widget/datetime/datetimepicker-extended.js, src/widget/distress/distresspicker.js, src/widget/file/filepicker.js, src/widget/geo/geopicker.js, src/widget/horizontal-choices/horizontalchoices.js, src/widget/note/notewidget.js, src/widget/radio/radiopicker.js, src/widget/select-desktop-bootstrap/selectpicker.js, src/widget/select-desktop/selectpicker.js, src/widget/select-mobile/selectpicker.js, src/widget/time/timepicker-extended.js
Looks like `data` is not used again after it was reassigned.
=> Remove no-op assignments from widgets

src/js/Form.js
Make references to `translator` consistent.
Ideally though, all code would probably refer to `fake-translator`, and leave this up to 3rd-parties to override with their own translator using e.g. browserify.
=> Reference the translator module consistently from widgets and Form.js

.travis.yml, test/karma.conf.js
Move timezone configuration from Travis config to karma config.  This should allow tests to pass with `npm test` on any machine.
=> Force timezone when running karma tests

src/js/plugins.js
Add support for clearing HTML `tel` inputs.  This means that if e.g. a widget changes an `<input type="text">` to `<input type="tel">`, the input will clear properly.
=> Add support for `tel` input type in clearInputs()

src/js/plugins.js
There might be a subtle reason (e.g. browser compatibility) why the code was written like it was, but it seems like you shouldn't need to handle the `data-previous-file-name` `data-loaded-file-name` attributes on input types which are not `type="file"`
=> Don't do file-specific work for other types of input

.travis.yml
Is there any value to testing against a specific version?  If not, then maybe we should switch from `6` to long term support (`lts/*`) or latest stable (`node`).  Or perhaps supporting a very old version will make browser compatibility a bit safer.  Any thoughts?
=> Test on travis on more node versions

app.js
Add console logging when the form transformation fails on the development HTML
page.
I added this logging while troubleshooting https://github.com/enketo/enketo-core/issues/486.
=> Report error when cannot transform form in dev

src/js/Form.js, test/forms/jr-choice-name.issue-490.xml, test/spec/form.spec.js
Fix regression in jr:choice-name() when the function call is embedded within
other function calls.
Closes #490 
@MartijnR I'm not really happy with either of the new tests supplied here:
1. the mocking required for the "unit" test is horrible
2. the integration test is probably better, but it seems a bit much that we have to include a new form just to test changes to a regex
One option to clean things up would be to expose the regex somehow, e.g. include it in a different file and `require(…)` it into both `Form.js` and a test file.  Seems a bit extreme to have a separate file for a single regex, though.
But if you're happy with the PR as-is, please merge.
=> Handle complex jr:choice-name() better

src/sass/core/_main.scss
=> fixed: breaking option label in grid theme not intelligent enough

src/js/input.js, src/widget/time/timepicker.js
Fixed:
- #649 default value not work for datetime with midnight value, it's a regression after 5.9.0.
- new issue introdueced by  #665.
=> Fixed: default value not work for datetime with midnight value, complete the fix of #665

src/sass/core/_print.scss, src/sass/grid/_print.scss, src/sass/grid/_widgets.scss, src/widget/text-print/text-print.scss
#166 
[OC-12196](https://jira.openclinica.com/browse/OC-12196)
example:
[Vital Signs-long-text-single-line.pdf](https://github.com/enketo/enketo-core/files/4152109/Vital.Signs-long-text-single-line.pdf)
=> fixed: OC: Print CRF/Casebook PDF long string(s) in text field overlaps

src/js/print.js
[#363](https://github.com/OpenClinica/enketo-express-oc/issues/363)
=> fixed: PDF endpoint creates image-map that overlaps in cell below with Grid theme

src/sass/grid/_print.scss
[#463](https://github.com/OpenClinica/enketo-express-oc/issues/463)
Using this XML [PostSurgery.xml.txt](https://github.com/enketo/enketo-core/files/6229185/PostSurgery.xml.txt) for testing also added `break-inside: avoid;` to make sure the header(title) move to the next pages too(when page breaks triggered).
=> fixed: Form Printing adding page breaks in the middle of an item

.travis.yml, package-lock.json, package.json, src/js/calculate.js, src/js/form.js, src/js/geolocation.js, src/js/input.js, src/js/readonly.js, src/widget/geo/geopicker.js, test/forms/setgeopoint.xml, test/helpers/geolocation.js, test/spec/form.spec.js, test/spec/setgeopoint.spec.js, test/spec/widget.geo.spec.js
This implements part of #579, setting a `geopoint` value based on the user's current location on load.
Notes:
- This currently does not work within a `repeat`, discussion in [these](https://github.com/enketo/enketo-core/issues/579#issuecomment-833133293) [comments](https://github.com/enketo/enketo-core/issues/579#issuecomment-833687549).
- This currently depends on a corresponding branch on my fork of `enketo-transformer` until https://github.com/enketo/enketo-transformer/pull/101 is released.
- I generalized the call to `Geolocation#getCurrentPosition`, but it's worth noting that the two calls which already existed had slightly different behavior. I chose the approach that explicitly handled accuracy over the approach which did not. If those were intentionally different I can make those …
=> Implement odk:setgeopoint for odk-instance-first-load events

src/js/form.js, test/spec/form.spec.js
Closes #781
See https://github.com/enketo/enketo-transformer/issues/100
=> Use new data-form-id attribute for formId

src/js/dom-utils.js, src/widget/textarea/textarea.js
[#484](https://github.com/OpenClinica/enketo-express-oc/issues/484)
=> fixed: OC: Text Multiline item with long values loads with widget condensed

src/widget/datetime/datetimepicker-extended.js, test/spec/widget.datetime.spec.js
- Ensures `originalInputValue` output consistently outputs seconds and milliseconds
- Relaxes test for the value of the widget's backing `datetime-local` input
=> Fix: Firefox DatetimepickerExtended tests

src/js/form-model.js, test/spec/formmodel.spec.js
…rg/xforms"-namespaced meta blocks are supported, #835
=> fixed: deprecatedID not added and populated properly if meta block is name-spaced with http://openrosa.org/xforms

src/js/page.js
In this PR:
- Pause multimedia (video and audio) from current page before navigating to next/prev page.
This code is a suggestion to fix [this issue](https://github.com/enketo/enketo-core/issues/816).
If this is okay, please consider backport it to 5.18.X, we noticed Enketo version 6.0.0 has a minimum of Node 14, at Medic we still support projects in Node 8 to 12 and won't be able to upgrade Enketo to 6.0.0 for a while.
=> Pause multimedia when switching pages

CHANGELOG.md, README.md
I missed that https://github.com/enketo/enketo-core/pull/860 forgot some updates.
Also adds a release checklist to reduce likelihood of omissions.
=> Add forgotten updates, release checklist

CHANGELOG.md, README.md, docs/index.html, package-lock.json, package.json
**Note:** I think we can safely remove `node-forge` from enketo-core, which doesn't directly use it anywhere I can find. Unless there's some dynamic usage I'm not aware of which wouldn't be provided by dependent projects, I'd prefer to remove it both as a dependency and as a step in the release process.
- Run `npm audit fix --production` to apply most important fixes
- N/A: Bump to major version if consumers have to make changes.
- GitHub Action will publish it to npm
=> Prepare for 6.0.4

src/widget/date/datepicker-extended.js, test/spec/widget.date.spec.js
When pasting values into the `datepicker-extended` widget, the following error is printed to the browser console:
```
Uncaught TypeError: Cannot read properties of null (reading 'length')
```
This is because the widget code is not getting the `originalEvent` from the jQuery event wrapper before unpacking the paste data.
(It is worth noting that the only other place the `getPasteData` util function is being used, in [`mask.js`](https://github.com/enketo/enketo-core/blob/51c5c2f494f1515a67355543b435f6aaa4b151b4/src/js/mask.js#L54), appears to work fine since it is passing the normal browser event (and not the jQuery event)).
Closes #877
=> Update `datepicker-extended` widget to properly unpack data from paste event

src/js/form.js, test/forms/randomize-outside-repeat.xml, test/spec/repeat.spec.js
Fixes #874.
As I mentioned in that issue, I'm not particularly fond of any solution I've come up with. But this is a pragmatic solution for now. I'm working on more general improvements to how we determine node relationships, but I think it's worth taking on this bit of tech debt in the meantime.
=> Fix: don't randomize unrelated itemsets outside repeat

.eslintrc.json, test/spec/calculate.spec.js, test/spec/form.spec.js, test/spec/format.spec.js, test/spec/formmodel.spec.js, test/spec/page.spec.js, test/spec/repeat.spec.js, test/spec/setvalue.spec.js, test/spec/utils.spec.js, test/spec/widget.analog-scale.spec.js, test/spec/widget.date.spec.js, test/spec/widget.thousands-sep.spec.js, test/spec/widget.time.spec.js
- Perform setup/teardown in beforeEach/afterEach rather than in the describe callback
- Use stubs rather than mutating shared values like config
- Use fake timers rather than relying on timeouts to work around async delays
- Style fixes
- Fix remaining ESLint warnings in affected files
- Continue to move towards async/await
- Allow Chai assertion statements
=> Improve test isolation

config.js, src/js/form.js, src/js/relevant.js, src/js/timers.js, test/karma.conf.js, test/spec/performance/evaluation-cascade.spec.js, tsconfig.json
Currently under the feature flag `config.experimentalOptimizations.computeAsync`, this allows the evaluation cascade to be performed asynchronously. This improves UI responsiveness for expensive calculations, especially when chained. Currently the feature flag can be enabled dynamically by appending `&computeAsync` to the URL when running the validation app.
This is achieved using [`requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)[^1], which calls the callback on when the event loop is idle or after `timeout` milliseconds, whichever comes first. The default `timeout` of `16` is approximately the number of milliseconds which would achieve 60 frames per second. This was chosen over `requestAnimationFrame` because the latter is higher …
=> Optionally recompute the evaluation cascade asynchronously

src/widget/geo/geopicker.scss
fix problem : It was impossible to move or select on the left of map when inputs was hidden
=> fix map with hidden geo-inputs when "hide-input" class is active

src/js/form.js, test/spec/form.spec.js
This is a slight variation on #893. The rationale for the difference is [explained here](https://github.com/enketo/enketo-core/pull/893#issuecomment-1132075839).
=> Fix: ensure evaluation cascade additions receive form context and update arguments

src/js/form-model.js, test/spec/formmodel.spec.js
Updates the selector used to pick the `meta` group element when adding an element for "deprecatedId".  Fixes an issue where the proper `meta` element is not selected if another (nested) `meta` element comes first.
Closes #890
=> Update meta selector used when setting deprecatedID

src/widget/geo/geopicker.js
Closes #902. Grouping these together, initially for visibility/feedback because they all affect the Leaflet UI and would be challenging to test and I want to get a sense of how much interest there is in adding those tests anyway.
=> Fix: preserve geopicker zoom, center map on user location on load, no error clicking pin

CHANGELOG.md, docs/Geopicker.html, docs/Nodeset.html, docs/js_form-model.js.html, docs/js_nodeset.js.html, docs/js_relevant.js.html, docs/module-relevant.html, docs/widget_geo_geopicker.js.html, package-lock.json, package.json
I did not update dependencies. I think we should update the release instructions to say we usually don't for point releases. It seems too risky to me -- we won't do any QA on patches typically.
I did take a quick look to see whether anything was high severity. https://github.com/chalk/ansi-regex/pull/37 is marked as high severity but it seems... not even kind of?
=> Prepare v6.1.2 release

src/widget/geo/geopicker.js
Fixes #920.
I considered using the static method `condition` for the `:not` case, which may have better performance characteristics, but that would split the logic more than it already is. I think it might be better still to rethink how widgets are identified and initialized in general.
=> Fix: use simpler selector for geopicker widgets

src/js/form.js
If you have a nested repeat group, `this.view.$.find('.or-group > h4').on('click', function () [...] ` is not triggered on the dynamic add group.
In this example :
At first I have 1 parent repeat group with 1 child repeat group.
I add a parent repeat group.
I can't click on the h4 of the second child repeat group to compact it
=> fix toggle or-appearance-compact with dynamic nesteed repeat group

src/widget/number-input/decimal-input.js, test/forms/number-input-widgets.xml, test/helpers/test-widget.js, test/spec/widget.number-input.spec.js
For future reference: this relies on explicit behavior in enketo-transformer which sets `step="any"` on decimal inputs. The affected tests have been updated accordingly to use the transformed result, rather than arbitrary HTML string literals.
=> Fix: allow arbitrary precision decimal values

src/widget/number-input/number-input.js
Moving `export default` below should also fix an oddity causing [this docs page](https://enketo.github.io/enketo-core/module.exports.html) to be generated.
=> Fix: don't clear decimals when switching French -> English

package-lock.json, package.json, src/widget/rank/rank-widget.js, src/widget/rank/rank-widget.scss
Fixes enketo/enketo-express#511
Verified on Moto G5 Chrome 109.0.5414.117
Not strictly necessary, but I also restricted touch dragging to the visible handle area (with some padding). I did this because testing on my own phone (iPhone, which turned out to reproduce the bug as well), I found it quite difficult to scroll anywhere near a rank question, and there's already a visible appearance of a handle on the side. Along with this change, I removed the "hover" effect on the full width rank options, because it no longer corresponds to the actionable area and could be confusing.
Happy to discuss those changes or make them separate, but I do think it would be a worse UX.
=> Fix: rank widget on touch devices

src/widget/geo/geopicker.js
Fixes #953. This is much narrower than the solution discussed there (detecting unused widgets on load so they don't continually query). It's probably worth doing as a separate change, but feels like overkill for this fix and probably best to evaluate its risk separately.
=> Fix: further simplify geopicker widget selector

CHANGELOG.md, package-lock.json, package.json
This change introduced regressions causing `TypeError`s when accessing jQuery extensions in Enketo Express
=> Fix: revert jQuery upgrade

src/js/form.js, src/js/relevant.js, src/js/widget.js, src/js/widgets-controller.js, src/widget/number-input/decimal-input.js, src/widget/number-input/integer-input.js, src/widget/number-input/number-input.js, test/spec/widget.number-input.spec.js
This change includes performance optimizations to perform fewer redundant operations in:
- `NumberInput` widgets (`DecimalInput`, `IntegerInput`). Their original implementation introduced a performance regression for forms with a large quantity of numeric inputs. Some of the pertinent change may benefit other widgets, i.e. they may be able to take advantage of `globalInit`, which is currently being used to cache the global form element rather than repeatedly querying for it, and to cache the localization behaviors in `DecimalInput`. Other changes move more decimal-specific logic from `NumberInput` to `DecimalInput` so that logic isn't performed needlessly by `IntegerInput`.
- Relevance changes when using the `excludeNonRelevant` setting. Prior to this change, the implementation would …
=> Performance improvements: NumberInput widgets, `excludeNonRelevant`

src/js/calculate.js, src/js/dom/collections.js, src/js/dom/features.js, src/js/dom/index.js, src/js/dom/refs.js, src/js/dom/tree-walker.js, src/js/event.js, src/js/form-model.js, src/js/form.js, src/js/input.js, src/js/itemset.js, src/js/language.js, src/js/output.js, src/js/page.js, src/js/progress.js, src/js/readonly.js, src/js/relevant.js, src/js/repeat.js, src/js/required.js, src/js/widget.js, src/js/widgets-controller.js, src/widget/time/timepicker.js, test/forms/collections.xml, test/spec/calculate.spec.js, test/spec/dom/collections.spec.js, test/spec/dom/tree-walker.spec.js, test/spec/input.spec.js, test/spec/itemset.spec.js, test/spec/repeat.spec.js, tsconfig.json
While there are a variety of changes in this PR, they all follow a common theme (as the title suggests): do less redundant work, specifically DOM work. All of the changes target code which:
- contribute significantly to many forms with clear optimization potential, as identified profiling those forms
- are either static in nature, or have clearly generalizable dynamic patterns
- have reasonably clear potential for caching, or can be statically identified as no-ops for a given form
The improvements are particularly pronounced on for forms with complex behavior around repeats. But highly complex forms **without** repeats may also benefit significantly from the caching portions of the changes.
The commit notes hopefully cover some of the more mundane and smaller changes, but I do want to go …
=> Optimizations: do less redundant work, part 2

src/js/input.js
Fixes https://github.com/enketo/enketo-core/issues/979.
Regression and fix described there, https://github.com/enketo/enketo-core/issues/979#issuecomment-1574444845:
> I found the change that caused this regression.
> https://github.com/enketo/enketo-core/commit/3accdd849662921b73966d7f29e3ffb109ddab56#diff-caad802f244c59940e6441fa0684b96b8c791470596c23de562f204c2dd1da40
> 
> It look like when dropping support for IE, this:
> 
> ```js
> // For IE11, we also need to strip the Left-to-Right marks \u200E...
> const ds = `${new Date()
>     .toLocaleDateString('en', {
>         month: 'short',
>         day: 'numeric',
>         year: 'numeric',
>     })
>     .replace(/\u200E/g, '')} ${value.replace(
>     /(\d\d:\d\d:\d\d)(\.\d{1,3})(\s?((\+|-)\d\d))(:)?(\d\d)?/,
>     '$1 GMT$3$7'
> )}`;
> …
```
=> Fix: Respect existing val of type='time'

src/js/widget.js, src/js/widgets-controller.js
=> Temporarily roll back buggy optimizations of enabling/disabling widget instances

src/widget/select-likert/likertitem.scss
Fixes #987.
This is a quick, hacky fix. I've included some notes in the stylesheet which should help to at least recall how the current design is applied, and hopefully also to inform considerations in the new theme's implementation of the Likert appearance.
=> Fix: don't display "ghost option" for itemsets with Likert appearance

src/js/widgets-controller.js
Fixes #989. This affects the built-in textarea and radiopicker widgets, as well as any custom widgets with `selector: 'form'`.
Like #990, this would ideally have been caught by tests. But I feel more confident that this is a sufficient change to keep this particular optimization intact, with tests to come when we reintroduce the optimizations rolled back in #990.
We should also seriously consider not using/supporting a `'form'` selector for widgets in general. To the extent it makes sense to have widget logic applied form-wide, we should have a design which addresses that separately from `selector`.
=> Fix: include widgets with 'form' selector

src/js/form-model.js
it seems that maps are faster, as this is assessed many time small speed improvement can have good effect
https://www.zhenghao.io/posts/object-vs-map
I cannot test (no set up working) but this should not require too many change to work
=> use map instead of object

src/js/widgets-controller.js, test/forms/repeat-count-widget-global-init.xml, test/spec/widgets-controller.spec.js
Fixes enketo/enketo-express#580.
=> Fix: global initialization of widgets where repeat count is zero

src/js/itemset.js, src/js/repeat.js, test/forms/repeat-multiple-shared-datalist-itemsets.xml, test/spec/itemset.spec.js
This fixes a case identified by the [recent pyxform change](https://github.com/XLSForm/pyxform/pull/614) to always generate secondary instances for selects. Hopefully the in-code commentary is enough elaboration on the nature of the bug and its fix.
=> Fix: multiple "static" itemset datalists in the same repeat
